import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/provider";
import Layout from "@/components/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers> 
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Layout/>
        <main className="ml-64 py-10 px-8 bg-gray-300">
        {children}
        </main>
      </body>
      </Providers>
      </ClerkProvider>
    </html>
  );
}
